name: Package mod

on:
  push:
    branches: [ "master" ]
    tags:
      - v0.*
      - v1.*

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Package pre-release version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      shell: pwsh
      run: .\build.ps1
    - name: Package for release
      if: startsWith(github.ref, 'refs/tags/')
      shell: pwsh
      run: .\build.ps1 ${{ github.ref_name }} 1

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.4.3
      with:
        name: content_editor_all
        path: "*.zip"
    - name: Upload files to release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "*.zip"
